### PR TITLE
vendor: common: Exclude ntfs-3g from artifact path requirement

### PR DESCRIPTION
**Pull request by StudioKeys**
Change-Id: I6253ac0b326f86ba7fd78f6babb9ee2242ba9133

This fixes the annoying NTFS bug we had for quite a long time!

### CODE REVIEW

**Comment by hmtheboy154** [comment]
what bug ?

**Comment by StudioKeys** [comment]
Connecting NTFS drives or USBs ask for a format in ext4 format.
Including this squashes that problem that is encountered!

**Comment by hmtheboy154** [comment]
oh those "Tap to fix" ?
I need to fix that too lol

**Comment by StudioKeys** [comment]
This adding doesn't need it the tap since it natively sees the drive and mounts it

**Comment by Jackeagle** [comment]
Merged

**Pull request closed without merging**
