### PR TITLE
Update custom_apns.py

### PR DESCRIPTION
**Pull request by iprouteth0**
Issue when building on ubuntu 20.10.  changed line 24 to reflect correct path.

### CODE REVIEW

**Review by Broly1 — APPROVED** [review]
Yes I had to change it to compile as well.

**Comment by iprouteth0** [comment]
Much obliged sir.  I'll close the request now.

**Comment by iprouteth0** [comment]
Not sure I was supposed to close it.  I'm a total noob with github

**Comment by ericswpark** [comment]
Hi, we've merged this pull request through Gerrit:

https://review.blissroms.org/c/platform_vendor_bliss/+/9361
https://github.com/BlissRoms/platform_vendor_bliss/commit/a7b81aabb60a30e13f1a6fd990110cf8b4a2d54c

Next time, please use our Gerrit instance available at review.blissroms.org to submit commits. Thanks!

**Pull request closed without merging**
